name: modulo4-Workflow

on:
  push:                             # Executa ao fazer push
  schedule:
    - cron: '0 * * * *'             # Executa a cada hora (UTC)

jobs:
  lint_job:
    name: Verificação com Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar Super Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check_tx_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Avisar se arquivos .tx foram adicionados ou modificados
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.tx$'; then
            echo "Arquivo .tx detectado"
          else
            echo "Nenhum arquivo .tx encontrado."
          fi
