name: modulo4-Workflow

on:
  push:                             
  schedule:
    - cron: '0 * * * *'             

jobs:
  job_1:
    name: Job 1 - Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Printa na tela
        uses: actions/hello-world-docker-action@v1


  job_2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Avisar se arquivos .tx foram adicionados ou modificados
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.tx$'; then
            echo "Arquivo .tx detectado"
          else
            echo "Nenhum arquivo .tx encontrado."
          fi
